const $=x=>document.getElementById(x);let run=false,state=0x6d2b79f5,formula=-1,raw=0,tickNo=0,cycle=1,wait=0,used=new Set(),usedF=new Set(),ws,retry,lastEpoch=0,pending=null,pnl=0,stake=1,w=0,l=0,ops=0;
function log(x){$('log').textContent=x+'\n'+$('log').textContent}
function avalanche(x){x=Math.imul(x^(x>>>16),0x21f0aaad);x=Math.imul(x^(x>>>15),0x735a2d97);return(x^(x>>>15))>>>0}
function chooseFormula(d){if(usedF.size===8)usedF.clear();let seed=((state^(d*97)^(tickNo*131))>>>0),f=seed%8;for(let k=0;k<8&&usedF.has(f);k++)f=(f+1+((seed>>>k)%7))%8;if(usedF.has(f))for(let z=0;z<8;z++)if(!usedF.has(z)){f=z;break}usedF.add(f);return f}
function mix(d){formula=chooseFormula(d);let x=state>>>0,n=d+1,t=tickNo+1;switch(formula){case 0:x=Math.imul(x^n,33)+t;break;case 1:x=(x+Math.imul(n+t,0x9e3779b1))>>>0;break;case 2:x=((x<<7)|(x>>>25))^(Math.imul(n,2654435761)+t);break;case 3:x=Math.imul((x+n+t)^0xa5a5a5a5,1597334677);break;case 4:x=(x^Math.imul(n+t,2246822519))+Math.imul(t,3266489917);break;case 5:x=Math.imul(x+(n<<16)^t,668265263);break;case 6:x=(x+Math.imul(n,374761393))^Math.imul(t,1274126177);break;default:x=Math.imul(x^(n+t),0x85ebca6b)^(x>>>13)}state=avalanche(x>>>0);raw=state%10}
function ui(d){if(d!==undefined)$('tick').textContent='D'+d;$('formula').textContent=formula<0?'—':'F'+formula;$('raw').textContent='D'+raw;$('cycle').textContent=cycle;$('accepted').textContent=used.size+'/10';$('wait').textContent=wait;$('used').textContent=used.size?[...used].map(x=>'D'+x).join(' · '):'NINGUNO';$('pnl').textContent=(pnl>=0?'+':'')+'$'+pnl.toFixed(2);$('stake').textContent='$'+stake.toFixed(2);$('win').textContent=w;$('match').textContent=l;$('ops').textContent=ops}
function completeCycle(){if(used.size===10){log('CICLO '+cycle+' COMPLETO · D0-D9 USADOS');cycle++;used.clear();wait=0}}
function tryTrade(){if(!run||pending)return;if(used.has(raw)){wait++;$('status').textContent='ESPERANDO RAW PENDIENTE';$('decision').textContent='SIN COMPRA · D'+raw+' YA USADO';$('reason').textContent='Otro tick alimentará la matemática. No se remapea.';ui();return}used.add(raw);ops++;pending={d:raw,stake,mode:$('mode').value};$('decision').textContent='DIFFER D'+raw+' · 1 TICK';$('reason').textContent='RAW D'+raw+' producido directamente por F'+formula+' · '+used.size+'/10 del ciclo';log('CICLO '+cycle+' · COMPRA '+pending.mode+' DIFFER D'+raw+' · $'+stake.toFixed(2));if(pending.mode==='REAL'){if(typeof realReady==='undefined'||!realReady){used.delete(raw);ops--;pending=null;run=false;$('status').textContent='REAL NO AUTENTICADO';ui();return}realTrade(raw,1,stake)}else{$('status').textContent='SIM · DIFFER D'+raw}ui()}
function settleSim(d){if(!pending||pending.mode!=='SIM')return;let p=pending;pending=null;if(d!==p.d){let gain=p.stake*.10;pnl+=gain;stake=p.stake+gain;w++;log('WIN SIM D'+p.d+' +$'+gain.toFixed(2))}else{pnl-=p.stake;stake=1;l++;log('MATCH SIM D'+p.d+' -$'+p.stake.toFixed(2))}completeCycle();if(pnl>=3){run=false;$('status').textContent='META +$3 · STOP'}ui()}
function onTick(d){tickNo++;if(pending&&pending.mode==='SIM')settleSim(d);mix(d);ui(d);if(run&&!pending)tryTrade()}
function connect(){clearTimeout(retry);ws=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');ws.onopen=()=>{ws.send(JSON.stringify({ticks:'R_75',subscribe:1}));$('status').textContent='TICKS CONECTADOS'};ws.onmessage=e=>{let m=JSON.parse(e.data);if(!m.tick)return;let ep=+m.tick.epoch;if(ep===lastEpoch)return;lastEpoch=ep;let p=Number(m.tick.pip_size||4),d=Number(Number(m.tick.quote).toFixed(p).slice(-1));onTick(d)};ws.onclose=()=>{pending=null;retry=setTimeout(connect,2500)}}
$('start').onclick=()=>{if($('mode').value==='REAL'&&(typeof realReady==='undefined'||!realReady)){$('status').textContent='REAL: CONECTA APP ID + PAT';return}pnl=0;stake=1;w=l=ops=0;pending=null;used.clear();wait=0;cycle=1;run=true;$('status').textContent='BUSCANDO RAW PENDIENTE';log('NUEVA SESIÓN · '+$('mode').value);ui();tryTrade()};$('stop').onclick=()=>{run=false;$('status').textContent='STOP MANUAL'};ui();connect();