const $=id=>document.getElementById(id);let running=false,pending=null,pnl=0,stake=1,wins=0,losses=0,ops=0,hist=[],tickNo=0,lastEpoch=0,ws,retry,cooldown=0,lastPick=null,samePickCount=0,observe=0;
function log(s){$('log').textContent=s+'\n'+$('log').textContent}
function ui(d){if(d!==undefined)$('tick').textContent='D'+d;$('pnl').textContent=(pnl>=0?'+':'')+'$'+pnl.toFixed(2);$('stake').textContent='$'+stake.toFixed(2);$('wins').textContent=wins;$('losses').textContent=losses;$('ops').textContent=ops;$('pick').textContent=lastPick===null?'—':'D'+lastPick}
function entropy(arr){let c=Array(10).fill(0);arr.forEach(x=>c[x]++);let n=arr.length,h=0;c.forEach(v=>{if(v){let p=v/n;h-=p*Math.log2(p)}});return h}
function selectDigit(){if(hist.length<120)return null;let w12=hist.slice(-12),w30=hist.slice(-30),w80=hist.slice(-80),prev=hist[hist.length-1],f12=Array(10).fill(0),f30=Array(10).fill(0),f80=Array(10).fill(0),tr=Array(10).fill(0);w12.forEach(x=>f12[x]++);w30.forEach(x=>f30[x]++);w80.forEach(x=>f80[x]++);for(let i=Math.max(1,hist.length-100);i<hist.length;i++)if(hist[i-1]===prev)tr[hist[i]]++;let H=entropy(w30),stability=Math.max(0,1-Math.abs(H-3.05)/1.4);let models=[];models.push(f12.map((v,d)=>({d,v})).sort((a,b)=>b.v-a.v)[0].d);models.push(f30.map((v,d)=>({d,v})).sort((a,b)=>b.v-a.v)[0].d);models.push(f80.map((v,d)=>({d,v})).sort((a,b)=>b.v-a.v)[0].d);models.push(tr.map((v,d)=>({d,v})).sort((a,b)=>b.v-a.v)[0].d);let votes=Array(10).fill(0);models.forEach(d=>votes[d]++);let scored=votes.map((v,d)=>({d,v,score:v*25+f12[d]*3+f30[d]+tr[d]*4})).filter(x=>x.d!==lastPick).sort((a,b)=>b.score-a.score),q=scored[0];if(!q)return null;let confidence=Math.min(99,Math.round(q.v*20+stability*18+Math.min(f12[q.d],3)*4));q.confidence=confidence;q.consensus=q.v;q.entropy=H;let strong=q.v>=2&&confidence>=58&&stability>=.35;return strong?q:null}
function openTrade(){if(!running||pending||cooldown||observe<4)return;let q=selectDigit();if(!q)return;if(q.d===lastPick)samePickCount++;else samePickCount=1;lastPick=q.d;let mode=$('mode').value,p={d:q.d,stake,mode};if(mode==='REAL'&&(!window.realReady||typeof window.sendRealTrade!=='function')){running=false;$('status').textContent='REAL NO CONECTADO';return}pending=p;observe=0;ops++;$('trade').textContent='COMPRA '+mode+' · DIFFER D'+p.d+' · $'+p.stake.toFixed(2)+' · 1 TICK';$('detail').textContent='NOVA PRO · confianza '+q.confidence+'% · consenso '+q.consensus+'/4 · entropía '+q.entropy.toFixed(2);$('status').textContent=mode==='SIM'?'DEMO ABIERTA':'REAL ENVIANDO';log('COMPRA '+mode+' DIFFER D'+p.d+' $'+p.stake.toFixed(2));ui();if(mode==='REAL')window.sendRealTrade(p.d,p.stake)}
function finish(profit,label){pnl+=profit;if(profit>0){wins++;stake=Math.max(1,stake+profit);$('trade').textContent='WIN '+label+' · '+(profit>=0?'+':'')+'$'+profit.toFixed(2)}else{losses++;stake=1;cooldown=2;$('trade').textContent='MATCH '+label+' · $'+profit.toFixed(2)}pending=null;observe=0;if(pnl>=3){running=false;$('status').textContent='META +$3 · STOP';log('META +$3 ALCANZADA')}else if(running)$('status').textContent='ANALIZANDO';ui()}
function settleSim(d){if(!pending||pending.mode!=='SIM')return;let p=pending;if(d===p.d)finish(-p.stake,'DEMO');else finish(p.stake*.10,'DEMO')}
function tick(d){tickNo++;if(running&&!pending)observe++;if(pending?.mode==='SIM')settleSim(d);hist.push(d);if(hist.length>600)hist.shift();if(cooldown){cooldown--;$('status').textContent='PAUSA '+cooldown+' TICKS';ui(d);return}ui(d);if(running&&!pending)openTrade()}
function connect(){clearTimeout(retry);ws=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');ws.onopen=()=>{ws.send(JSON.stringify({ticks_history:'R_75',count:120,end:'latest',style:'ticks',req_id:1}))};ws.onmessage=e=>{let m=JSON.parse(e.data);if(m.history?.prices){let p=Number(m.pip_size||4);hist=m.history.prices.map(x=>Number(Number(x).toFixed(p).slice(-1)));ws.send(JSON.stringify({ticks:'R_75',subscribe:1,req_id:2}));$('status').textContent='LISTO'}if(m.tick){let ep=+m.tick.epoch;if(ep===lastEpoch)return;lastEpoch=ep;let p=Number(m.tick.pip_size||4);tick(Number(Number(m.tick.quote).toFixed(p).slice(-1)))}};ws.onclose=()=>{pending=null;retry=setTimeout(connect,2500)}}
$('start').onclick=()=>{if($('mode').value==='REAL'&&!window.realReady){$('status').textContent='CONECTA REAL PRIMERO';return}pnl=0;stake=1;wins=losses=ops=0;pending=null;cooldown=0;lastPick=null;samePickCount=0;observe=0;running=true;$('status').textContent='ANALIZANDO';$('trade').textContent='SESIÓN '+$('mode').value+' INICIADA';log('NUEVA SESIÓN '+$('mode').value);ui()};$('stop').onclick=()=>{running=false;$('status').textContent='STOP MANUAL'};window.realSettlement=(profit)=>finish(profit,'REAL');ui();connect();