const $=id=>document.getElementById(id);let running=false,pending=null,pnl=0,stake=1,wins=0,losses=0,ops=0,hist=[],tickNo=0,lastEpoch=0,ws,retry,cooldown=0,lastPick=null,samePickCount=0,observe=0;
function log(s){$('log').textContent=s+'\n'+$('log').textContent}
function ui(d){if(d!==undefined)$('tick').textContent='D'+d;$('pnl').textContent=(pnl>=0?'+':'')+'$'+pnl.toFixed(2);$('stake').textContent='$'+stake.toFixed(2);$('wins').textContent=wins;$('losses').textContent=losses;$('ops').textContent=ops;$('pick').textContent=lastPick===null?'—':'D'+lastPick}
function selectDigit(){if(hist.length<80)return null;let a=hist.slice(-80),short=hist.slice(-12),mid=hist.slice(-30),freq=Array(10).fill(0),fs=Array(10).fill(0),fm=Array(10).fill(0);a.forEach(x=>freq[x]++);short.forEach(x=>fs[x]++);mid.forEach(x=>fm[x]++);let candidates=freq.map((n,d)=>{let pressure=fs[d]*4+fm[d]*1.5+n*.35;let gap=0;for(let i=hist.length-1;i>=0;i--){if(hist[i]===d)break;gap++;if(gap>=30)break}return{d,pressure,gap,score:pressure+Math.min(gap,12)*.18}}).sort((x,y)=>y.score-x.score);if(lastPick!==null)candidates=candidates.filter(x=>x.d!==lastPick);let q=candidates[0];if(!q)return null;let strong=q.pressure>=13&&q.gap<=8;return strong?q:null}
function openTrade(){if(!running||pending||cooldown||observe<4)return;let q=selectDigit();if(!q)return;if(q.d===lastPick)samePickCount++;else samePickCount=1;lastPick=q.d;let mode=$('mode').value,p={d:q.d,stake,mode};if(mode==='REAL'&&(!window.realReady||typeof window.sendRealTrade!=='function')){running=false;$('status').textContent='REAL NO CONECTADO';return}pending=p;observe=0;ops++;$('trade').textContent='COMPRA '+mode+' · DIFFER D'+p.d+' · $'+p.stake.toFixed(2)+' · 1 TICK';$('detail').textContent='Entrada seleccionada por motor NOVA · score '+q.score;$('status').textContent=mode==='SIM'?'DEMO ABIERTA':'REAL ENVIANDO';log('COMPRA '+mode+' DIFFER D'+p.d+' $'+p.stake.toFixed(2));ui();if(mode==='REAL')window.sendRealTrade(p.d,p.stake)}
function finish(profit,label){pnl+=profit;if(profit>0){wins++;stake=Math.max(1,stake+profit);$('trade').textContent='WIN '+label+' · '+(profit>=0?'+':'')+'$'+profit.toFixed(2)}else{losses++;stake=1;cooldown=2;$('trade').textContent='MATCH '+label+' · $'+profit.toFixed(2)}pending=null;observe=0;if(pnl>=3){running=false;$('status').textContent='META +$3 · STOP';log('META +$3 ALCANZADA')}else if(running)$('status').textContent='ANALIZANDO';ui()}
function settleSim(d){if(!pending||pending.mode!=='SIM')return;let p=pending;if(d===p.d)finish(-p.stake,'DEMO');else finish(p.stake*.10,'DEMO')}
function tick(d){tickNo++;if(running&&!pending)observe++;if(pending?.mode==='SIM')settleSim(d);hist.push(d);if(hist.length>600)hist.shift();if(cooldown){cooldown--;$('status').textContent='PAUSA '+cooldown+' TICKS';ui(d);return}ui(d);if(running&&!pending)openTrade()}
function connect(){clearTimeout(retry);ws=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');ws.onopen=()=>{ws.send(JSON.stringify({ticks_history:'R_75',count:120,end:'latest',style:'ticks',req_id:1}))};ws.onmessage=e=>{let m=JSON.parse(e.data);if(m.history?.prices){let p=Number(m.pip_size||4);hist=m.history.prices.map(x=>Number(Number(x).toFixed(p).slice(-1)));ws.send(JSON.stringify({ticks:'R_75',subscribe:1,req_id:2}));$('status').textContent='LISTO'}if(m.tick){let ep=+m.tick.epoch;if(ep===lastEpoch)return;lastEpoch=ep;let p=Number(m.tick.pip_size||4);tick(Number(Number(m.tick.quote).toFixed(p).slice(-1)))}};ws.onclose=()=>{pending=null;retry=setTimeout(connect,2500)}}
$('start').onclick=()=>{if($('mode').value==='REAL'&&!window.realReady){$('status').textContent='CONECTA REAL PRIMERO';return}pnl=0;stake=1;wins=losses=ops=0;pending=null;cooldown=0;lastPick=null;samePickCount=0;observe=0;running=true;$('status').textContent='ANALIZANDO';$('trade').textContent='SESIÓN '+$('mode').value+' INICIADA';log('NUEVA SESIÓN '+$('mode').value);ui()};$('stop').onclick=()=>{running=false;$('status').textContent='STOP MANUAL'};window.realSettlement=(profit)=>finish(profit,'REAL');ui();connect();