const $=x=>document.getElementById(x);let seq=[],run=false,pending=null,lastBought=null,pnl=0,stake=1,w=0,l=0,ops=0,winStreak=0,liveTicks=[],dangerActive=false,watchDigits=new Set(),discardUntil=Array(10).fill(0),tickNo=0;
function log(x){$('log').textContent=x+'\n'+$('log').textContent}
function entropy(a){let c=Array(10).fill(0);a.forEach(x=>c[x]++);return c.reduce((h,x)=>{if(!x)return h;let p=x/a.length;return h-p*Math.log2(p)},0)}
function analyze(){if(seq.length<120)return null;let s=Array(10).fill(0),e=Array.from({length:10},()=>[]);
for(const n of [10,20,40,80]){let c=Array(10).fill(0);seq.slice(-n).forEach(x=>c[x]++);let sd=Math.sqrt(n*.09);for(let d=0;d<10;d++){let z=(c[d]-n*.1)/sd;if(z<0){s[d]+=Math.min(2.2,-z);e[d].push('Z'+n+'='+z.toFixed(2))}}}
let c=Array(10).fill(0);seq.slice(-80).forEach(x=>c[x]++);let chi=c.reduce((q,x)=>q+(x-8)*(x-8)/8,0),g=c.reduce((q,x)=>x?q+2*x*Math.log(x/8):q,0);for(let d=0;d<10;d++)if(c[d]<8){if(chi>=8){s[d]+=.35;e[d].push('CHI='+chi.toFixed(1))}if(g>=8){s[d]+=.3;e[d].push('G='+g.toFixed(1))}}
let r=seq.slice(-200),last=r.at(-1),tr=Array.from({length:10},()=>Array(10).fill(1));for(let i=1;i<r.length;i++)tr[r[i-1]][r[i]]++;let row=tr[last],rs=row.reduce((q,x)=>q+x,0);for(let d=0;d<10;d++){let p=row[d]/rs;if(p<.1){s[d]+=(.1-p)*15;e[d].push('M1='+(p*100).toFixed(1)+'%')}}
let rc=Array(10).fill(0);seq.slice(-30).forEach(x=>rc[x]++);for(let d=0;d<10;d++)s[d]-=Math.max(0,rc[d]-3)*.25;let pool=s.map((v,d)=>({d,s:v,e:e[d]})).filter(x=>x.d!==lastBought&&discardUntil[x.d]<=tickNo);if(!pool.length)return null;let min=Math.min(...pool.map(x=>x.s)),weighted=pool.map(x=>({...x,w:1+Math.max(0,x.s-min)})),total=weighted.reduce((q,x)=>q+x.w,0),rpick=Math.random()*total,pick=weighted[0];for(const x of weighted){rpick-=x.w;if(rpick<=0){pick=x;break}}return {ok:true,p:pick,H:entropy(seq.slice(-100)),chi,g}}
function ui(){$('pnl').textContent=(pnl>=0?'+':'')+'$'+pnl.toFixed(2);$('stake').textContent='$'+stake.toFixed(2);$('win').textContent=w;$('match').textContent=l;$('ops').textContent=ops}

function decide(){if(!run||pending)return;let q=analyze();if(!q||!q.ok){$('status').textContent=seq.length<120?'CALIBRANDO '+seq.length+'/120':'SIN ENTRADA';return}let p=q.p,dur=1;lastBought=p.d;ops++;if($('mode').value==='REAL'){if(typeof realReady==='undefined'||!realReady){run=false;$('status').textContent='REAL NO AUTENTICADO';return}pending={d:p.d,stake,mode:'REAL'};realTrade(p.d,dur,stake)}else{pending={d:p.d,left:dur,stake,mode:'SIM'}}$('decision').textContent='D'+p.d+' · '+dur+'T';$('evidence').textContent=p.e.join(' · ')+' | H='+q.H.toFixed(3)+' CHI='+q.chi.toFixed(1)+' G='+q.g.toFixed(1);$('status').textContent='SIM DIFFER D'+p.d;ui()}
function learnDanger(){if(!dangerActive||!liveTicks.length)return;let n=liveTicks.length,c=Array(10).fill(0);liveTicks.forEach(x=>c[x]++);let mean=n/10,sd=Math.sqrt(n*.09),hot=c.map((v,d)=>({d,n:v,z:sd?(v-mean)/sd:0})).filter(x=>x.z>=0.65&&x.n>mean).sort((a,b)=>b.z-a.z);const counts=c.map((v,d)=>'D'+d+':'+v).join('  ');$('evidence').textContent='VIVO '+n+'T · '+counts+' | SUSPENDIDOS: '+(hot.length?hot.map(x=>'D'+x.d).join(','):'NINGUNO');}
function settle(d){if(!pending||pending.mode==='REAL')return;if(--pending.left>0)return;let p=pending;if(d!==p.d){let x=p.stake*.1;pnl+=x;stake=p.stake+x;w++;winStreak++;watchDigits.add(p.d);log('WIN D'+p.d+' · VIGILANDO D'+p.d+' · RACHA '+winStreak);if(!dangerActive){dangerActive=true;log('ANÁLISIS VIVO ACTIVADO DESDE WIN 1 · '+liveTicks.length+' TICKS');learnDanger()}}else{pnl-=p.stake;stake=1;l++;winStreak=0;if(!dangerActive)liveTicks=[];log('MATCH D'+p.d)}pending=null;if(pnl>=3){run=false;$('status').textContent='META +$3 · STOP'}ui()}
function tick(d){tickNo++;if(watchDigits.has(d)){watchDigits.delete(d);discardUntil[d]=tickNo+10;log('D'+d+' APARECIÓ DESPUÉS DEL WIN · DESCARTADO 10 TICKS')}seq.push(d);if(seq.length>2500)seq.shift();if(run&&pending&&pending.mode==='SIM'){liveTicks.push(d);if(dangerActive)learnDanger()}settle(d);if(run&&!pending)decide()}

let ws=null,retry=null,lastEpoch=0;
function connect(){clearTimeout(retry);ws=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');ws.onopen=()=>{ws.send(JSON.stringify({ticks_history:'R_75',count:700,end:'latest',style:'ticks',req_id:1}));$('status').textContent='CONECTADO · MATH PRO'};ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.history&&m.history.prices){const p=Number(m.pip_size||4);seq=m.history.prices.map(x=>Number(Number(x).toFixed(p).slice(-1)));ws.send(JSON.stringify({ticks:'R_75',subscribe:1,req_id:2}));$('status').textContent='TICKS EN VIVO';decide()}if(m.tick){const ep=+m.tick.epoch;if(ep===lastEpoch)return;lastEpoch=ep;const p=Number(m.tick.pip_size||4);tick(Number(Number(m.tick.quote).toFixed(p).slice(-1)))}};ws.onclose=()=>{pending=null;retry=setTimeout(connect,2500)}}
$('start').onclick=()=>{if($('mode').value==='REAL'&&(typeof realReady==='undefined'||!realReady)){$('status').textContent='REAL: autentica primero';return}pnl=0;stake=1;w=l=ops=0;pending=null;lastBought=null;winStreak=0;liveTicks=[];dangerActive=false;watchDigits.clear();discardUntil.fill(0);tickNo=0;run=true;ui();log('MATH PRO INICIADO');decide()};
$('stop').onclick=()=>{run=false;pending=null;$('status').textContent='STOP MANUAL'};
ui();connect();
