const $=x=>document.getElementById(x);let seq=[],run=false,pending=null,lastBought=null,pnl=0,stake=1,w=0,l=0,ops=0,winStreak=0,liveTicks=[],dangerActive=false,watchDigits=new Set(),discardUntil=Array(10).fill(0),matchRisk=Array(10).fill(0),tickNo=0,repeatBlocked=null,matchStreak=0,pauseUntil=0,accState=0,bestWinStreak=0,mixFormula=-1,mixDigit=0;
function log(x){$('log').textContent=x+'\n'+$('log').textContent}
async function syncCloud(){try{const r=await fetch('cloud-state.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)return;const m=await r.json();if(Array.isArray(m.history)&&m.history.length){seq=m.history.slice(-2500);rebuildAccumulator()}if(Array.isArray(m.watch_digits))m.watch_digits.forEach(d=>watchDigits.add(Number(d)));if(Array.isArray(m.discard_remaining))m.discard_remaining.forEach((v,d)=>{discardUntil[d]=Math.max(discardUntil[d]||0,tickNo+(Number(v)||0))});if(Number.isInteger(m.last_bought))lastBought=m.last_bought;if(Number.isInteger(m.repeat_blocked))repeatBlocked=m.repeat_blocked;if(Array.isArray(m.match_risk))m.match_risk.forEach((v,d)=>matchRisk[d]=Math.max(matchRisk[d],Number(v)||0));log('NUBE SINCRONIZADA · '+new Date((m.updated_epoch||0)*1000).toLocaleString()+' · VIGILADOS '+([...watchDigits].length?[...watchDigits].map(d=>'D'+d).join(','):'NINGUNO'));}catch(e){log('NUBE NO DISPONIBLE · CONTINÚA LOCAL')}}
function updateRepeatBlock(){let a=seq.slice(-20),c=Array(10).fill(0);a.forEach(x=>c[x]++);let mx=Math.max(...c),leaders=c.map((v,d)=>({d,v})).filter(x=>x.v===mx);let next=mx>=3&&leaders.length===1?leaders[0].d:null;if(next!==repeatBlocked){if(repeatBlocked!==null)log('D'+repeatBlocked+' LIBERADO POR REPETICIÓN');repeatBlocked=next;if(repeatBlocked!==null)log('D'+repeatBlocked+' SUSPENDIDO · MÁS REPETIDO EN 20 TICKS')}}
function mix32(x){x=Math.imul(x^(x>>>16),0x21f0aaad);x=Math.imul(x^(x>>>15),0x735a2d97);return (x^(x>>>15))>>>0}
function dynamicMix(state,d,i,forcedFormula=null){let raw=forcedFormula===null?((state^(d*97)^(i*131))>>>0)%8:forcedFormula,f=raw;if(f===mixFormula)f=(f+1+(((state>>>11)^d^i)%7))%8;let x=state>>>0,n=(d+1)>>>0,t=(i+1)>>>0;switch(f){case 0:x=Math.imul(x^n,33)+t;break;case 1:x=(x+Math.imul(n+t,0x9e3779b1))>>>0;break;case 2:x=((x<<7)|(x>>>25))^(Math.imul(n,2654435761)+t);break;case 3:x=Math.imul((x+n+t)^0xa5a5a5a5,1597334677);break;case 4:x=(x^Math.imul(n+t,2246822519))+Math.imul(t,3266489917);break;case 5:x=Math.imul(x+(n<<16)^t,668265263);break;case 6:x=(x+Math.imul(n,374761393))^Math.imul(t,1274126177);break;default:x=Math.imul(x^(n+t),0x85ebca6b)^(x>>>13)}return {state:mix32(x>>>0),formula:f}}
function rebuildAccumulator(){accState=0x6d2b79f5;mixFormula=-1;let start=Math.max(0,seq.length-700);for(let i=start;i<seq.length;i++){let r=dynamicMix(accState,seq[i],i-start);accState=r.state;mixFormula=r.formula}mixDigit=accState%10}
function feedAccumulator(d){let r=dynamicMix(accState,d,tickNo);accState=r.state;mixFormula=r.formula;mixDigit=accState%10}
function accumulatorDigit(){return mixDigit}
function entropy(a){let c=Array(10).fill(0);a.forEach(x=>c[x]++);return c.reduce((h,x)=>{if(!x)return h;let p=x/a.length;return h-p*Math.log2(p)},0)}
function riskSnapshot(){if(seq.length<120)return null;let c=Array(10).fill(0);seq.slice(-80).forEach(x=>c[x]++);let chi=c.reduce((q,x)=>q+(x-8)*(x-8)/8,0),g=c.reduce((q,x)=>x?q+2*x*Math.log(x/8):q,0);return {H:entropy(seq.slice(-100)),chi,g}}
function accumulatorPick(){let base=accumulatorDigit(),step=1+((accState>>>8)%9);for(let k=0;k<10;k++){let d=(base+k*step)%10;if(discardUntil[d]<=tickNo&&d!==repeatBlocked&&matchRisk[d]<3.5)return {d,e:['MIX_F'+mixFormula,'RAW=D'+base,'ESTADO='+accState,'SALTO='+step+(k?' · DESVIO='+k:'')]}}return null}
function analyze(){if(seq.length<120)return null;let stats=riskSnapshot(),pick=accumulatorPick();if(!pick)return null;return {ok:true,p:pick,H:stats.H,chi:stats.chi,g:stats.g}}
function streakSignal(){let a=seq.slice(-4);if(a.length<2)return null;let last=a.at(-1),hits=a.filter(x=>x===last).length;if(hits>=2&&hits<=3&&discardUntil[last]<=tickNo&&last!==repeatBlocked)return {d:last,e:['RACHA_CORTA='+hits+'/4']};return null}
function ui(){$('pnl').textContent=(pnl>=0?'+':'')+'$'+pnl.toFixed(2);$('stake').textContent='$'+stake.toFixed(2);$('win').textContent=w;$('match').textContent=l;$('ops').textContent=ops;if($('acc'))$('acc').textContent='D'+accumulatorDigit();if($('formula'))$('formula').textContent='F'+mixFormula;if($('streak'))$('streak').textContent=winStreak;if($('beststreak'))$('beststreak').textContent=bestWinStreak}

function decide(){if(!run||pending)return;if(tickNo<pauseUntil){$('status').textContent='PAUSA MATCH · '+(pauseUntil-tickNo)+' TICKS';return}let q=analyze();if(!q||!q.ok){$('status').textContent=seq.length<120?'CALIBRANDO '+seq.length+'/120':'SIN ENTRADA';return}let p=q.p,dur=1;lastBought=p.d;ops++;if($('mode').value==='REAL'){if(typeof realReady==='undefined'||!realReady){run=false;$('status').textContent='REAL NO AUTENTICADO';return}pending={d:p.d,stake,mode:'REAL'};realTrade(p.d,dur,stake)}else{pending={d:p.d,left:dur,stake,mode:'SIM'}}$('decision').textContent='MIX F'+mixFormula+' → DIFFER D'+p.d+' · '+dur+'T';$('evidence').textContent=p.e.join(' · ')+' | H='+q.H.toFixed(3)+' CHI='+q.chi.toFixed(1)+' G='+q.g.toFixed(1);$('status').textContent='ACC DIRECTO · SIM DIFFER D'+p.d;ui()}
function learnDanger(){if(!dangerActive||!liveTicks.length)return;let n=liveTicks.length,c=Array(10).fill(0);liveTicks.forEach(x=>c[x]++);let mean=n/10,sd=Math.sqrt(n*.09),hot=c.map((v,d)=>({d,n:v,z:sd?(v-mean)/sd:0})).filter(x=>x.z>=0.65&&x.n>mean).sort((a,b)=>b.z-a.z);const counts=c.map((v,d)=>'D'+d+':'+v).join('  ');$('evidence').textContent='VIVO '+n+'T · '+counts+' | SUSPENDIDOS: '+(hot.length?hot.map(x=>'D'+x.d).join(','):'NINGUNO');}
function settle(d){if(!pending||pending.mode==='REAL')return;if(--pending.left>0)return;let p=pending;if(d!==p.d){let x=p.stake*.1;pnl+=x;stake=p.stake+x;w++;winStreak++;bestWinStreak=Math.max(bestWinStreak,winStreak);matchStreak=0;if(discardUntil[p.d]<=tickNo){watchDigits.add(p.d);log('WIN D'+p.d+' · VIGILANDO D'+p.d+' · RACHA '+winStreak)}else{log('WIN D'+p.d+' · D'+p.d+' SIGUE DESCARTADO '+(discardUntil[p.d]-tickNo)+' TICKS')};if(!dangerActive){dangerActive=true;log('ANÁLISIS VIVO ACTIVADO DESDE WIN 1 · '+liveTicks.length+' TICKS');learnDanger()}}else{pnl-=p.stake;stake=1;l++;winStreak=0;matchStreak++;if(matchStreak>=2){pauseUntil=Math.max(pauseUntil,tickNo+5);matchStreak=0;log('2 MATCH SEGUIDOS · PAUSA 5 TICKS · PNL Y PROGRESIÓN CONSERVADOS')}watchDigits.delete(p.d);discardUntil[p.d]=Math.max(discardUntil[p.d],tickNo+10);matchRisk[p.d]=Math.min(5,matchRisk[p.d]+2);if(!dangerActive)liveTicks=[];log('MATCH D'+p.d+' · D'+p.d+' BLOQUEADO 10 TICKS')}pending=null;if(pnl>=3){run=false;$('status').textContent='META +$3 · STOP'}ui()}
function tick(d){tickNo++;matchRisk=matchRisk.map(x=>Math.max(0,x*.96));if(watchDigits.has(d)){watchDigits.delete(d);discardUntil[d]=tickNo+10;log('D'+d+' APARECIÓ DESPUÉS DEL WIN · DESCARTADO 10 TICKS')}seq.push(d);if(seq.length>2500)seq.shift();feedAccumulator(d);updateRepeatBlock();liveTicks.push(d);if(dangerActive)learnDanger();settle(d);if(run&&!pending)decide()}

let ws=null,retry=null,lastEpoch=0;
function connect(){clearTimeout(retry);ws=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');ws.onopen=()=>{ws.send(JSON.stringify({ticks_history:'R_75',count:700,end:'latest',style:'ticks',req_id:1}));$('status').textContent='CONECTADO · MATH PRO'};ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.history&&m.history.prices){const p=Number(m.pip_size||4);seq=m.history.prices.map(x=>Number(Number(x).toFixed(p).slice(-1)));rebuildAccumulator();ws.send(JSON.stringify({ticks:'R_75',subscribe:1,req_id:2}));$('status').textContent='TICKS EN VIVO';decide()}if(m.tick){const ep=+m.tick.epoch;if(ep===lastEpoch)return;lastEpoch=ep;const p=Number(m.tick.pip_size||4);tick(Number(Number(m.tick.quote).toFixed(p).slice(-1)))}};ws.onclose=()=>{pending=null;retry=setTimeout(connect,2500)}}
$('start').onclick=()=>{if($('mode').value==='REAL'&&(typeof realReady==='undefined'||!realReady)){$('status').textContent='REAL: autentica primero';return}pnl=0;stake=1;w=l=ops=0;pending=null;lastBought=null;winStreak=0;bestWinStreak=0;matchStreak=0;pauseUntil=0;run=true;ui();log('MATH PRO INICIADO · APRENDIZAJE CONSERVADO');decide()};
$('stop').onclick=()=>{run=false;pending=null;$('status').textContent='STOP MANUAL'};
ui();syncCloud().finally(connect);
