const $=x=>document.getElementById(x);let seq=[],run=false,pending=null,lastBought=null,pnl=0,stake=1,w=0,l=0,ops=0,winStreak=0,streakTicks=[],dangerDigits=new Set();
function log(x){$('log').textContent=x+'\n'+$('log').textContent}
function entropy(a){let c=Array(10).fill(0);a.forEach(x=>c[x]++);return c.reduce((h,x)=>{if(!x)return h;let p=x/a.length;return h-p*Math.log2(p)},0)}
function analyze(){if(seq.length<120)return null;let s=Array(10).fill(0),e=Array.from({length:10},()=>[]);
for(const n of [10,20,40,80]){let c=Array(10).fill(0);seq.slice(-n).forEach(x=>c[x]++);let sd=Math.sqrt(n*.09);for(let d=0;d<10;d++){let z=(c[d]-n*.1)/sd;if(z<0){s[d]+=Math.min(2.2,-z);e[d].push('Z'+n+'='+z.toFixed(2))}}}
let c=Array(10).fill(0);seq.slice(-80).forEach(x=>c[x]++);let chi=c.reduce((q,x)=>q+(x-8)*(x-8)/8,0),g=c.reduce((q,x)=>x?q+2*x*Math.log(x/8):q,0);for(let d=0;d<10;d++)if(c[d]<8){if(chi>=8){s[d]+=.35;e[d].push('CHI='+chi.toFixed(1))}if(g>=8){s[d]+=.3;e[d].push('G='+g.toFixed(1))}}
let r=seq.slice(-200),last=r.at(-1),tr=Array.from({length:10},()=>Array(10).fill(1));for(let i=1;i<r.length;i++)tr[r[i-1]][r[i]]++;let row=tr[last],rs=row.reduce((q,x)=>q+x,0);for(let d=0;d<10;d++){let p=row[d]/rs;if(p<.1){s[d]+=(.1-p)*15;e[d].push('M1='+(p*100).toFixed(1)+'%')}}
let ranked=s.map((v,d)=>({d,s:v,e:e[d]})).filter(x=>!dangerDigits.has(x.d)&&x.d!==lastBought).sort((a,b)=>b.s-a.s),best=ranked[0];if(!best)return null;let band=ranked.filter(x=>x.s>=2.8&&x.e.length>=3&&x.s>=best.s-.8);return {ok:band.length>0,p:band.length?band[Math.floor(Math.random()*band.length)]:best,H:entropy(seq.slice(-100)),chi,g}}
function ui(){$('pnl').textContent=(pnl>=0?'+':'')+'$'+pnl.toFixed(2);$('stake').textContent='$'+stake.toFixed(2);$('win').textContent=w;$('match').textContent=l;$('ops').textContent=ops}

function decide(){if(!run||pending)return;let q=analyze();if(!q||!q.ok){$('status').textContent=seq.length<120?'CALIBRANDO '+seq.length+'/120':'SIN ENTRADA';return}let p=q.p,dur=1+Math.floor(Math.random()*2);lastBought=p.d;ops++;if($('mode').value==='REAL'){if(typeof realReady==='undefined'||!realReady){run=false;$('status').textContent='REAL NO AUTENTICADO';return}pending={d:p.d,stake,mode:'REAL'};realTrade(p.d,dur,stake)}else{pending={d:p.d,left:dur,stake,mode:'SIM'}}$('decision').textContent='D'+p.d+' · '+dur+'T';$('evidence').textContent=p.e.join(' · ')+' | H='+q.H.toFixed(3)+' CHI='+q.chi.toFixed(1)+' G='+q.g.toFixed(1);$('status').textContent='SIM DIFFER D'+p.d;ui()}
function learnDanger(){let c=Array(10).fill(0);streakTicks.forEach(x=>c[x]++);let top=c.map((n,d)=>({d,n})).sort((a,b)=>b.n-a.n||a.d-b.d).slice(0,3);dangerDigits=new Set(top.map(x=>x.d));log('PELIGROSOS '+top.map(x=>'D'+x.d+'('+x.n+')').join(' · '));winStreak=0;streakTicks=[]}
function settle(d){if(!pending||pending.mode==='REAL')return;if(--pending.left>0)return;let p=pending;if(d!==p.d){let x=p.stake*.1;pnl+=x;stake=p.stake+x;w++;winStreak++;log('WIN D'+p.d+' · RACHA '+winStreak+'/10');if(winStreak>=10)learnDanger()}else{pnl-=p.stake;stake=1;l++;winStreak=0;streakTicks=[];log('MATCH D'+p.d+' · muestra descartada')}pending=null;if(pnl>=3){run=false;$('status').textContent='META +$3 · STOP'}ui()}
function tick(d){seq.push(d);if(seq.length>2500)seq.shift();if(run&&pending&&pending.mode==='SIM')streakTicks.push(d);settle(d);if(run&&!pending)decide()}

let ws=null,retry=null,lastEpoch=0;
function connect(){clearTimeout(retry);ws=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');ws.onopen=()=>{ws.send(JSON.stringify({ticks_history:'R_75',count:700,end:'latest',style:'ticks',req_id:1}));$('status').textContent='CONECTADO · MATH PRO'};ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.history&&m.history.prices){const p=Number(m.pip_size||4);seq=m.history.prices.map(x=>Number(Number(x).toFixed(p).slice(-1)));ws.send(JSON.stringify({ticks:'R_75',subscribe:1,req_id:2}));$('status').textContent='TICKS EN VIVO';decide()}if(m.tick){const ep=+m.tick.epoch;if(ep===lastEpoch)return;lastEpoch=ep;const p=Number(m.tick.pip_size||4);tick(Number(Number(m.tick.quote).toFixed(p).slice(-1)))}};ws.onclose=()=>{pending=null;retry=setTimeout(connect,2500)}}
$('start').onclick=()=>{if($('mode').value==='REAL'&&(typeof realReady==='undefined'||!realReady)){$('status').textContent='REAL: autentica primero';return}pnl=0;stake=1;w=l=ops=0;pending=null;lastBought=null;winStreak=0;streakTicks=[];dangerDigits.clear();run=true;ui();log('MATH PRO INICIADO');decide()};
$('stop').onclick=()=>{run=false;pending=null;$('status').textContent='STOP MANUAL'};
ui();connect();
